name:                rain-ml
version:             0.1.0
github:              "elpinal/rain-ml"
license:             MIT
author:              "El Pin Al"
maintainer:          ""
copyright:           "2018 El Pin Al"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/elpinal/rain-ml#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10.8.2
- containers >= 0.6.0.1
- freer-simple >= 1.1.0.0
- heaps >= 0.3.6
- megaparsec >= 7.0.4
- optparse-applicative >= 0.14.3.0
- parser-combinators >= 1.0.0
- safe-exceptions >= 0.1.7.0
- transformers >= 0.5.5.0

library:
  source-dirs: src

executables:
  rain-ml:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rain-ml

tests:
  rain-ml-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rain-ml
    - hspec
